output_dir: results

data:
    name: dummy
    n_train: 10000
    n_valid: 0
    shard: True
    sample_shape: [64, 64, 64, 4]
    target_shape: [4]
    batch_size: 1 # no. of samples per IPU
    n_epochs: 30

model:
    name: cosmoflow
    input_shape: [64, 64, 64, 4]
    target_size: 4
    dropout: 0.2

optimizer:
    name: Adadelta
    lr: 0.5
    lr_scaling: none

train:
    loss: mse
    metrics: ['mae']
    
ipu_config:
    iterations_per_loop: 5000 # number of batches processed per session.run
    num_ipus: 1
