DATA:
  DATASET: 'imagenet'
  IMG_SIZE: [224,224]
  INTERPOLATION: 'bicubic'
  ZIP_MODE: False
  CACHE_MODE: 'part'
  PIN_MEMORY: True
  NUM_WORKERS: 32
  BATCH_SIZE: 4

IPU:
  NUM_REPLICAS: 2
  GRADIENT_ACCUMULATION_STEPS: 64
  DEVICE_ITERATIONS: 1
  IPUS: 8
  LAYERS_PER_IPU: [2,2,3,3,5,5,2,2]

TRAIN:
  START_EPOCH: 0
  EPOCHS: 300
  WARMUP_EPOCHS: 20
  WEIGHT_DECAY: 0.05
  BASE_LR: 0.001
  WARMUP_LR: 5e-7
  MIN_LR: 5e-6
  # Clip gradient norm
  CLIP_GRAD: 5.0
  # Auto resume from latest checkpoint
  AUTO_RESUME: True
  # Whether to use gradient checkpointing to save memory
  # could be overwritten by command line argument
  USE_CHECKPOINT: False

  # LR scheduler
  LR_SCHEDULER:
    NAME: 'cosine'
    # Epoch interval to decay LR, used in StepLRScheduler
    DECAY_EPOCHS: 30
    # LR decay rate, used in StepLRScheduler
    DECAY_RATE: 0.1

  LOSS_SCALING: 1024
  # Optimizer
  OPTIMIZER:
    NAME: 'adamw'
    # Optimizer Epsilon
    EPS: 1e-8
    # Optimizer Betas
    BETAS: (0.9, 0.999)
    # SGD momentum
    MOMENTUM: 0.9

PRECISION: ['float','float']
AUG:
  SSL_AUG: True
  COLOR_JITTER: 0.4
  # Use AutoAugment policy. "v0" or "original"
  AUTO_AUGMENT: 'rand-m9-mstd0.5-inc1'
  # Random erase prob
  REPROB: 0.25
  # Random erase mode
  REMODE: 'pixel'
  # Random erase count
  RECOUNT: 1
  # Mixup alpha, mixup enabled if > 0
  MIXUP: 0.8
  # Cutmix alpha, cutmix enabled if > 0
  CUTMIX: 1.0
  # Cutmix min/max ratio, overrides alpha and enables cutmix if set
  CUTMIX_MINMAX: None
  # Probability of performing mixup or cutmix when either/both is enabled
  MIXUP_PROB: 1.0
  # Probability of switching to cutmix when both mixup and cutmix enabled
  MIXUP_SWITCH_PROB: 0.5
  # How to apply mixup/cutmix params. Per "batch", "pair", or "elem"
  MIXUP_MODE: 'batch'

TEST:
  CROP: True
MODEL:
  TYPE: linear
  DEVICE: ipu
  NUM_CLASSES: 1000
  NAME: swin_tiny__patch4_window7_224
  DROP_PATH_RATE: 0.5
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE:  7

